### ISSUE TITLE
socket hang up in local dfx canister

### ISSUE THREAD

**Issue by AuroraLantean** [dfinity/node-ic0#1]
I was trying to make a call to a local canister via NodeJs:
const nameDip721 = await localDip721.call('nameDip721');
And the command is **node --es-module-specifier-resolution=node src/node/index2.js**
```
`/mnt/sda3/internet_computer/dip721-nft-container/node_modules/node-fetch/lib/index.js:1491
			reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
			       ^
FetchError: request to http://localhost:4943/api/v2/canister/ryjl3-tyaaa-aaaaa-aaaba-cai/query failed, reason: socket hang up
    at ClientRequest.<anonymous> (/mnt/sda3/internet_computer/dip721-nft-container/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketOnEnd (node:_http_client:514:9)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}

Node.js v19.4.0
`
Did I miss something? Thanks

**Comment by rvanasa** [comment]
Thanks for submitting this issue. What `dfx` version are you using? Also, are you able to access the canister via the link displayed after running `dfx deploy`? I'll try to recreate this on my end.

**Comment by AuroraLantean** [comment]
Hi my dfx version: 0.12.1. The Candid UI provided by `**dfx deploy** works fine. Thanks

**Comment by rvanasa** [comment]
Found the issue; working on a fix right now.

**Comment by rvanasa** [comment]
Alright, let me know if upgrading to `0.2.3` fixes the issue.

**Comment by AuroraLantean** [comment]
Do I need this node_compatibility in the dfx.json file for my NodeJs to call on the local canister?
```
      "declarations": {
        "node_compatibility": true
      }

**Comment by rvanasa** [comment]
The `declarations` config will only affect the code generated by the `dfx generate` command (which might be a useful alternative to `ic0` if you're mostly working with local canisters).

**Comment by AuroraLantean** [comment]
Ok. After upgrading  ic0 to 0.2.3, without that node compatibility declarations, query functions work. but update functions do not work:
```
let balance1 = await localDip721.call('balanceOfDip721', nft_to_principal);
const out = await localDip721.call( 'mintDip721forall',  nft_to_principal,  nft_metadata);

```
I got the same error:  type: 'system',   errno: 'ECONNRESET',  code: 'ECONNRESET'. Please advise.

**Comment by rvanasa** [comment]
Okay, I suppose that's a good sign! I'll take a look at this. 

It's possible that Node 19.x could be part of the problem (the underlying `@dfinity/agent` package has only been tested up to 18.x). However, I'll try to confirm and see if there's a way to fix this if this ends up being the case.

**Comment by rvanasa** [comment]
Do you run into the same issue when importing and calling the `index.js` file created by `dfx generate`? Here's [an example from a frontend project](https://github.com/rvanasa/vite-react-motoko/blob/0419621dfc0a71bfd3072d9dcff489ec89b7be15/src/App.tsx#L6) in case this helps clarify the difference from this npm package. 

If you receive the same `ECONNRESET` error message, that narrows it down to a bug with `@dfinity/agent` on Node 19.x.

**Comment by AuroraLantean** [comment]
NodeJs told me "Directory import is not supported resolving ES modules", so I had to import the index.js file, not the direction:  import { dip721_nft_container } from '../declarations/dip721_nft_container/index.js';
but then this error came up immediately without me calling any function with that import:
`
```

/mnt/sda3/internet_computer/dip721-nft-container/node_modules/@dfinity/agent/lib/cjs/agent/http/index.js:150
                throw new Error('Must specify a host to connect to.');
                      ^

``Error: Must specify a host to connect to.
    at new HttpAgent (/mnt/sda3/internet_computer/dip721-nft-container/node_modules/@dfinity/agent/lib/cjs/agent/http/index.js:150:23)
    at createActor (file:///mnt/sda3/internet_computer/dip721-nft-container/src/declarations/dip721_nft_container/index.js:11:34)
    at file:///mnt/sda3/internet_computer/dip721-nft-container/src/declarations/dip721_nft_container/index.js:37:37
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
`
And after changing NodeJs to 18.13.0, that error above remains the same

**Comment by AuroraLantean** [comment]
Wait a minute. This code should be used inside the IC frontend:
 import { dip721_nft_container } from '../../declarations/dip721_nft_container';

But now ic0 works with NodeJs v18.13.0 !
```
import ic from 'ic0';
const balance = await localDip721.call('balanceOfDip721', nft_to_principal);
const out = await localDip721.call('mintDip721forall', nft_to_principal,  nft_metadata);
```

**Comment by rvanasa** [comment]
Hooray! Glad that this ended up working for you.
